# Generated by Django 5.2.13 on 2026-04-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ready_to_withdraw',
        ),
    ]
