# Generated by Django 5.2.13 on 2026-04-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_remove_profile_ready_to_withdraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptodeposit',
            name='crypto_type',
            field=models.CharField(max_length=100),
        ),
    ]
