# Generated by Django 5.2.13 on 2026-04-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_alter_cryptodeposit_crypto_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailshistory',
            name='link_anchor',
            field=models.CharField(blank=True, null=True),
        ),
    ]
