# Generated by Django 5.2.13 on 2026-04-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_emailshistory_link_anchor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_withdrawal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
